name: Destroy GKE Cluster

on:
  workflow_dispatch:

jobs:
  delete-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Delete Cluster
        run: |
          gcloud container clusters delete confluent-kraft-lab \
            --zone us-central1-a \
            --quiet
